# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DeepLearning',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/DeepLearning',
                'lib_path': 'DeepLearning'},
  'syms': {'DeepLearning.core': {'DeepLearning.core.foo': ('core.html#foo', 'DeepLearning/core.py')}}}
